@startuml

entity Users

Users : uuid id
Users : string name
Users : string email
Users : date ceated_at

Users : create()
Users : update()
Users : delete()

entity Regions

uuid id : Regions

Regions : get()


@enduml
